import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// const inter = Inter({
// 	variable: "--font-inter",
// 	subsets: ["latin"],
// });

const figtree = Figtree({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-figtree",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${figtree.className}  antialiased min-h-screen `}
			>
				<div
					className="fixed inset-0 bg-cover bg-center bg-no-repeat -z-10"
					style={{
						backgroundImage: `url('/background.png')`,
					}}
				/>
				<div className="relative z-10">{children}</div>
			</body>
		</html>
	);
}
